name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.4.5'
      SERVERPOD_PASSWORD_database: '0Pg2wdcwgDVkhX3r2n8RNRKXst1Pbk6j'
      SERVERPOD_PASSWORD_redis: 'OaSA_IQrsYjI2vSHfYH214nUzbiDWtip'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: tracking_training_server
        run: docker compose up --quiet-pull --build -d

      - name: Install dependencies
        working-directory: tracking_training_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: tracking_training_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: tracking_training_server
        run: serverpod generate

      - name: Run tests
        working-directory: tracking_training_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: tracking_training_server
        run: docker compose down -v
